name: release-please

on:
  workflow_dispatch:
    inputs:
      is_bump_minor:
        description: "bump-minor-pre-major"
        default: false
        required: true
        type: boolean
      is_bump_patch_for_minor_pre_major:
        description: "bump-patch-for-minor-pre-major"
        default: false
        required: true
        type: boolean

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: eslint-config-yehezgun
          bump-minor-pre-major: ${{ inputs.is_bump_minor }}
          bump-patch-for-minor-pre-major: ${{ inputs.is_bump_patch_for_minor_pre_major }}
          # The logic below handles the npm publication:
      - uses: actions/checkout@v2
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
